### ISSUE TITLE
Include Multiplatform Artifacts in Builds

### ISSUE THREAD

**Issue by deckerbd** [Ellerbach/docfx-companion-tools#11]
Hey there, love the utilities!

I routinely hop between Windows and macOS, and noticed while there's binaries published for Windows in this repo and on Chocolatey, there's none published for macOS or on [Homebrew](https://brew.sh/). Currently I'm pulling the source and rebuilding against macOS instead of Windows. I was wondering if in addition to Windows binaries, if there could be consideration in publishing release artifacts for macOS and Linux going forward as well. I can help with a PR if desired.

**Comment by Ellerbach** [comment]
Hi @deckerbd, I guess it's something we can do. Have Windows, MacOS and Linux artifact published as well. That will require to adjust a bit the workflow. On the to do list but please don't expect anything in a short period of time!

**Comment by cathalnoonan** [comment]
Would you consider releasing these as dotnet tools? This would avoid needing to produce multi-platform builds by instead relying on the dotnet sdk installed on the consumer's machine (Windows/macOS/Linux).

The docs for creating a dotnet tool suggest [adding the dotnet-tool related properties to the .csproj files](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create#package-the-tool), but this approach might affect the existing build process used in this repo to build/publish the `.exe`s to chocolatey. 

It's also possible to pass these dotnet-tool related properties to the `dotnet pack` command using the `-p` argument (without modifying the .csproj files). See below as an example.
https://github.com/cathalnoonan/docfx-companion-tools/blob/e5fd18e9462b3b8fe23e744e5ca25ed60fdc6f6a/pack_dotnet_tools.sh

After packing the nupkgs, the packages can be pushed using `dotnet nuget push` (with an API key for authenticating to NuGet.org).

Assuming the tools are published to NuGet, the consumers would install the parts they need by running:
```sh
# (replace DocFxTocGenerator below with the other tools as necessary)

# Install the tool locally in the current folder
dotnet new tool-manifest
dotnet tool install DocFxTocGenerator

# Install the tool globally
dotnet tool install -g DocFxTocGenerator
```

**Comment by Ellerbach** [comment]
@cathalnoonan, yes definitely. Let me have a look on how to release those like this quickly.
@mtirion I will have a look at this.

**Comment by Ellerbach** [comment]
@cathalnoonan it's done:

![image](https://user-images.githubusercontent.com/8145578/229828387-9a375c73-d5ae-43ce-8d8b-913863987f84.png)

You can install each tool separately.

**Comment by Ellerbach** [comment]
And all works as expected on a Mac:

![image](https://user-images.githubusercontent.com/8145578/230110033-54458bae-1255-4412-a855-c3ec98a91e70.png)

You can run properly the tools:

![image](https://user-images.githubusercontent.com/8145578/230110184-e56f9d8e-8642-4263-bf2e-bb606e50ac24.png)

So @deckerbd you just need to have .NET 6.0 or higher installed and add the `~/.dotnet/tool` to your path and you can enjoy all the tools!
