### ISSUE TITLE
DocLinkChecker - Add support for relative path from root directory reference

### ISSUE THREAD

**Issue by jrmoulckers** [Ellerbach/docfx-companion-tools#12]
Please add DocLinkChecker support for using the `~` character to represent relative paths from the root of a DocFX project.

This is essential for deeper project structures that utilize the `.attachments` folder at the root of a project.

This behavior is also officially supported by DocFX, but results in a failure using the companion tool suite:
> Not found: ~/.attachments/abc.png

 From the [DocFX Tutorial page on Links and Cross References](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html):
> Sometimes you may find it's complicated to calculate relative path between two files. DocFX also supports paths that start with ~ to represent a path relative to the root directory of your project (i.e., where docfx.json is located). This kind of path will also be validated and resolved during build.

**Comment by Ellerbach** [comment]
> Please add DocLinkChecker support for using the `~` character to represent relative paths from the root of a DocFX project.

You are right. We'll look at this.

**Comment by Ellerbach** [comment]
Closing issue as the PR is now merged. thanks again for bringing it!
