### ISSUE TITLE
Why don't you support .NET 7?

### ISSUE THREAD

**Issue by bdovaz** [Ellerbach/docfx-companion-tools#45]
.NET 8 has been released very recently and it is obvious but .NET 7 why not?

Everything that manages our pipeline targets .NET 7 and just for this tool I have to install the .NET 6 runtime.

Would you accept a PR that targets .NET 7 (and .NET 8 if you want)?

Thanks!

The error:

```
You must install or update .NET to run this application.

App: /home/ci/.dotnet/tools/DocLinkChecker
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /home/ci/data/agent/_work/_tool/dotnet

The following frameworks were found:
  7.0.14 at [/home/ci/data/agent/_work/_tool/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by Ellerbach** [comment]
How do you install the tool? It should be transparent if you have a more recent version installed.

**Comment by bdovaz** [comment]
Following README.md:

https://github.com/Ellerbach/docfx-companion-tools#dotnet-tool

**Comment by Ellerbach** [comment]
Then it should definitely work fine:

![image](https://github.com/Ellerbach/docfx-companion-tools/assets/8145578/5e8cc4f1-c63c-4538-af2e-495fa40b7b2f)

As you can see, .NET 7.0 installed, installing the tool thru dotnet tool and running it

**Comment by Ellerbach** [comment]
And work same way on a Linux box but you have to add the `--roll-forward Major` option:

![image](https://github.com/Ellerbach/docfx-companion-tools/assets/8145578/67869324-6cce-4487-a90f-18e35c0ee9bf)

More info here: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet#rollforward

**Comment by bdovaz** [comment]
But you did not get the output from `dotnet --list-runtimes`.

I'm sure you have the .NET 6 runtime installed as well besides the .NET 7 runtime.

`dotnet --version` outputs (I think) the most recent version you have

**Comment by Ellerbach** [comment]
> `dotnet --version` outputs (I think) the most recent version you have

Yes, you are correct. Now, for the Linux side, I only have 1:

![image](https://github.com/Ellerbach/docfx-companion-tools/assets/8145578/373c8769-549d-4f2b-8507-07f06da3a1e8)

Just use ` ~/.dotnet/tools/DocLinkChecker --roll-forward Major` (adjust for the path if any) and you'll be good to go

**Comment by Ellerbach** [comment]
PR #46 created to bring clarification in the main README.

Let me know if this is clear enough.

**Comment by bdovaz** [comment]
That's very good clarification, thank you @Ellerbach
