### ISSUE TITLE
Unexpected ERROR Not found

### ISSUE THREAD

**Issue by davesmits** [Ellerbach/docfx-companion-tools#50]
I am trying to integrate doclinkchecker and I am getting this error

```
./platform/Admin/Action-Hub/BuildAnAction.md 54:1
***ERROR Not found: ~/.attachments/image-ac695c92-679c-4bb6-9ce8-f02e64d6308e.png
```

Now  the problem is that the file is there. Its even visible when I publish the generated website.
<img width="325" alt="image" src="https://github.com/Ellerbach/docfx-companion-tools/assets/3148438/2cb40f18-0f23-410e-8ec8-5e54db6e1eb2">

I am just not sure how to troubleshoot this. I saw #12  brought support for ~

**Comment by Ellerbach** [comment]
Is it the only image like this? Or do you have others?
Are you running DocFX with the proper root directory?
Any minimal example to reproduce more than the screen capture? Like a minimum file code and the command line you are running (also from where)

**Comment by mtirionMSFT** [comment]
@davesmits sorry for the delay. I have added support for using the ~, but there is something you need to be aware off. As we don't know the location of the docfx.json file, we assume that file to be in the documentation root folder. That's the only thing we can check. If the docfx.json file is somewhere else, the actual generation of links in the DocFx processor might end up with wrong links.

As soon as PR #59 is merged I'll make sure to publish the change asap.
