### ISSUE TITLE
DocLinkChecker throws warning when using Tabs

### ISSUE THREAD

**Issue by david-okeefe** [Ellerbach/docfx-companion-tools#51]
I added a Linux tab and a Windows tab to a sample page using the example from the DocFX documentation below.

https://dotnet.github.io/docfx/docs/markdown.html?tabs=linux%2Cdotnet#tabs

When running DocLinkChecker against this page, I receive the following two warnings.

DocLinkChecker version 1.18.0
***WARNING Heading 'tab/linux' not found in 'D:\a\docfx\docfx\docs\guides\index.md'

***WARNING Heading 'tab/windows' not found in 'D:\a\docfx\docfx\docs\guides\index.md'

Can DocLinkChecker be updated to ignore the links associated with Tabs?

**Comment by david-okeefe** [comment]
I discovered this issue was referenced in #29 as well.

https://github.com/Ellerbach/docfx-companion-tools/issues/29#issuecomment-1798862318

**Comment by mtirionMSFT** [comment]
@david-okeefe Included this in fixing #29. Solution is in PR #58 which will be released soon.
