### ISSUE TITLE
Feature Request : Add option to skip title casing in toc item titles

### ISSUE THREAD

**Issue by pvshn** [Ellerbach/docfx-companion-tools#54]
We use this extension to generate `toc.yml` for Python documentation using Sphinx. In this case, we want the toc titles to be exactly the same as that of the filename. 
This feature request is to add a configuration option to skip [automatic title casing](https://github.com/Ellerbach/docfx-companion-tools/blob/main/src/DocFxTocGenerator/TocGenerator.cs#L661) for toc titles.

We could generate an .override file but the feature I propose is more efficient.

**Comment by Ellerbach** [comment]
If you want to go for a PR with this addition, feel free to add it. So far, it's not really on the priority list.
