### ISSUE TITLE
Empty folders with populated child folders get skipped

### ISSUE THREAD

**Issue by rwrife** [Ellerbach/docfx-companion-tools#55]
In the screenshot attached, if there is a child folder that is basically contains no direct child .md files but has child folders that contain .md files it appears that those children are completely omitted from processing.  Also, I noticed that in this scenario if you attempt the multitoc generation option the tool crashes with an exception.

![image](https://github.com/Ellerbach/docfx-companion-tools/assets/1685329/99c9368e-0c9a-4a56-a4e4-693a5e7f3856)

**Comment by Ellerbach** [comment]
Can you propose a short file structure so that we can reproduce the issue, find the root cause and possibly fix it?

**Comment by rwrife** [comment]
Yeah let me see what I can put together, we have a couple repos inside Microsoft that have the issue that I could share internally, but I'll come up with something more public.

**Comment by Ellerbach** [comment]
@rwrife we do have the new version out. Can you check this is fixed for you?
