### ISSUE TITLE
Feature request:  add recursive directory support to DocLinkChecker

### ISSUE THREAD

**Issue by jamescl604** [Ellerbach/docfx-companion-tools#6]
Great utility.   It would be great if it could recursively traverse subfolders of the specified directory looking for markdown and .attachments in each folder found.   In our DocFx, we put documentation for each component into their own folders, each also has it's own attachments folder.   It's possible to script repeated calls but would be great to have it built in.

**Comment by Ellerbach** [comment]
Thanks for the proposition @jamescl604. We'll see if others need the same. So far, we used for this situation different tasks in the pipeline. Reason was to split the results and make it more atomic.
Now, why not having this option. If we decide to add that, it won't be super soon. So feel free as well to submit a PR.
Note that we may add as well the possibility to check other folder that .attachements as some other code as repo may use different ones.

**Comment by mtirionMSFT** [comment]
@jamescl604 this should be covered by a new version of DocLinkChecker that's in the making. Please have a look at https://github.com/Ellerbach/docfx-companion-tools/tree/doclinkchecker-upgrade to see if this is what you would expect. The tool will be released in the coming weeks.
