### ISSUE TITLE
DocLinkChecker returns different exit codes than documented

### ISSUE THREAD

**Issue by hashtag-squirrel** [Ellerbach/docfx-companion-tools#63]
When running the DocLinkChecker from our pipeline, we get different exit codes than we should. 

The documentation states we should receive 1000 (warnings only) and 1001 (with errors), however, testing showed that we received 232 and 233 respectively instead. In the screenshot you can see the exit code echo'ed out via script. 

![image](https://github.com/user-attachments/assets/df518afd-0b55-41aa-8f64-c56b66beda66)

Am I missing something here or is this indeed a bug?

**Comment by mtirionMSFT** [comment]
@hashtag-squirrel I validated the return codes, but they are the values described in the README. I tested in a command shell where I did an `echo %errorlevel%` after the DocLinkChecker command and was always as reported.

How did you get the "233" value? Which environment and shell?

**Comment by mtirionMSFT** [comment]
@hashtag-squirrel  I was able to see that same behavior. Investigating...

**Comment by mtirionMSFT** [comment]
@hashtag-squirrel found it. To fix this I have to change return values. Discussing breaking change.
![image](https://github.com/user-attachments/assets/85d2823e-1b5f-4fa5-a912-c7ba78ad3fdc)
