### ISSUE TITLE
DocFxTocGenerator: .order file not being respected for folders

### ISSUE THREAD

**Issue by sxmanton** [Ellerbach/docfx-companion-tools#86]
The logs show that it is detecting my .order files and I see them being correctly applied for folders whose only contents is files, but for folders with only subfolders or a mix of folders and files, it is applying the default ordering (i.e. it does respect the FilesFirst or FoldersFirst or All, but is alphabetical otherwise)

**Comment by mtirionMSFT** [comment]
@sxmanton I have reproduced this. Looking into it.
