### ISSUE TITLE
Can not install docfx-companion-tools via chocolatey

### ISSUE THREAD

**Issue by alexander-lysenko-88** [Ellerbach/docfx-companion-tools#9]
Hi

I'm trying to install the tool using the recommended command `choco install docfx-companion-tools` but it fails with the following error:
```
Failures
 - docfx-companion-tools - docfx-companion-tools not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.
```

Any ideas regarding how this can be fixed? :)

**Comment by Ellerbach** [comment]
hi @alexander-lysenko-88 , yes: patience... Unfortunately, it still under (manual) validation on the Chocolatey team...
@mtirionMSFT you may have more news?

Note: we've adjusted all the docs and the tools are under validation since last week. You can use the "old" way in the mean time: cloning and build the tool. Just go back a bit in the history and you'll find out. Hopefully this will be solved quickly.

**Comment by mtirionMSFT** [comment]
@alexander-lysenko-88 @Ellerbach unfortunately it's blocked in the publishing process and the information is not very clear to me. I'm trying to contact the admins to get it resolved asap. Sorry for the delay! I'll post here when it's resolved.

**Comment by mtirionMSFT** [comment]
@alexander-lysenko-88 it's waiting in a queue for review. It looks like it's about to be picked up. In the meantime you CAN already install from Chocolatey, but you have to do it like this:

```Powershell
choco install docfx-companion-tools --version=1.1.0
```

**Comment by alexander-lysenko-88** [comment]
@Ellerbach, @mtirionMSFT, thank you guys for assistance!
workaround with installation of explicit version works fine 👍

**Comment by mtirionMSFT** [comment]
@alexander-lysenko-88 @Ellerbach Chocolatey package is published. You can now safely use:

```Powershell
choco install docfx-companion-tools
```
